### ISSUE TITLE
demo isn't work

### ISSUE THREAD

**Issue by riskers** [jordansinger/Hook#29]
the demo isn't work absolutely!
why?

**Comment by codeKonami** [comment]
Yeah the demo is definitely broken. There is only an iframe in the content. 

The index.html in the repo doesn't work either. It seems that you need to add some content to be able to scroll a little to make the pull-to-refresh working.

**Comment by canvs** [comment]
the same problem。。。

**Comment by dawsonbotsford** [comment]
Demo is broken

**Comment by fengnovo** [comment]
+1

**Comment by cybernet** [comment]
after 2 years, this isnt fixed ?
